services:
  percona:
    image: percona:8.0.33-25-centos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iznik
      MYSQL_DATABASE: iznik
    ports:
      - 8306:3306

  postgres:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      POSTGRES_DB: iznik
      POSTGRES_PASSWORD: iznik
      POSTGRES_USER: root
    ports:
     - 8432:5432

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - percona
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=percona
      - PMA_USER=root
      - PMA_PASSWORD=iznik

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  beanstalkd:
    image: schickling/beanstalkd
    container_name: 'beanstalkd'
    ports:
      - "11300:11300"

#  Spam Assassin fails to start with rules issue.  No spam checking will occur until we fix this.
#
#  spamassassin-app:
#    image: tiredofit/spamassassin
#    container_name: spamassassin-app
#    ports:
#      - 783:783
#    volumes:
#      - ./logs/spamassassin:/logs
#      - ./conf:/config
#      - ./data:/data
#    environment:
#      - CONTAINER_NAME=spamassassin-app
#    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  # Freegle images.
  apiv2:
    build: https://github.com/Freegle/iznik-server-go.git
    depends_on:
      - percona
    restart: always
    ports:
      - "8192:8192"
    environment:
      - MYSQL_HOST=percona
      - MYSQL_PORT=3306

  apiv1:
    build: https://github.com/Freegle/iznik-server.git
    depends_on:
      - percona
      - beanstalkd
      - mailhog
      - redis
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MYSQL_HOST=percona
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=iznik
      - PHEANSTALK_SERVER=beanstalkd
      - REDIS_CONNECT=redis
      - IMAGE_DOMAIN=apiv1

  freegle:
    build: https://github.com/Freegle/iznik-nuxt3.git
    depends_on:
      - apiv1
      - apiv2
    restart: always
    ports:
      - "8080:3000"

  modtools:
    build: https://github.com/Freegle/iznik-nuxt.git
    depends_on:
      - apiv1
      - apiv2
    restart: always
    ports:
      - "8082:3000"
