#!/bin/bash
# Parameterize host ports in docker-compose.yml for multi-instance support.
#
# Usage:
#   ./parameterize-ports.sh <offset>              # Patch docker-compose.yml AND print .env vars
#   ./parameterize-ports.sh <offset> --env-only    # Only print .env vars (append to .env)
#   ./parameterize-ports.sh 0                      # Use default ports (no offset)
#
# This replaces hardcoded host ports in docker-compose.yml with environment
# variable references that have defaults matching the original values.
# A separate .env file then overrides these with offset values.

set -e

OFFSET="${1:-0}"
ENV_ONLY="${2:-}"

# Port mapping: VAR_NAME=original_host_port
# Each entry corresponds to a specific port line in docker-compose.yml
declare -A PORT_MAP=(
    [PORT_TRAEFIK_HTTP]=80
    [PORT_TRAEFIK_API]=8192
    [PORT_TRAEFIK_DASHBOARD]=8080
    [PORT_PHPMYADMIN]=8086
    [PORT_MAILPIT_WEB]=8025
    [PORT_MAILPIT_SMTP]=1025
    [PORT_SPAMASSASSIN]=783
    [PORT_RSPAMD]=11334
    [PORT_TUSD]=1080
    [PORT_STATUS]=8081
    [PORT_AI_SUPPORT]=8083
    [PORT_APIV1_SSH]=1023
    [PORT_APIV1_HTTP]=83
    [PORT_APIV1_HTTP2]=8181
    [PORT_APIV2]=8193
    [PORT_APIV2_LIVE]=8194
    [PORT_FREEGLE_DEV_LOCAL]=3002
    [PORT_FREEGLE_DEV_LIVE]=3005
    [PORT_FREEGLE_PROD_LOCAL]=3012
    [PORT_MODTOOLS_DEV_LOCAL]=3003
    [PORT_MODTOOLS_DEV_LIVE]=3006
    [PORT_MODTOOLS_PROD_LOCAL]=3013
    [PORT_LOKI]=3100
    [PORT_POSTFIX_SMTP]=25
    [PORT_MCP_SANITIZER]=8084
)

# Generate .env content
generate_env() {
    echo ""
    echo "# === Port configuration (offset: $OFFSET) ==="
    echo "# Generated by parameterize-ports.sh"
    echo "# To use default ports, remove or comment out these lines."
    for var in $(echo "${!PORT_MAP[@]}" | tr ' ' '\n' | sort); do
        original=${PORT_MAP[$var]}
        new_port=$((original + OFFSET))
        echo "${var}=${new_port}"
    done
}

if [ "$ENV_ONLY" = "--env-only" ]; then
    generate_env
    exit 0
fi

# Patch docker-compose.yml to use environment variables
COMPOSE_FILE="docker-compose.yml"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "ERROR: $COMPOSE_FILE not found in current directory." >&2
    exit 1
fi

echo "Patching $COMPOSE_FILE to use port environment variables..."

# Back up original
cp "$COMPOSE_FILE" "${COMPOSE_FILE}.original"

# Apply substitutions. Each sed command targets a specific port pattern.
# We match the full port line to avoid ambiguity.

# Traefik (reverse-proxy) ports
sed -i 's|"80:80"|"${PORT_TRAEFIK_HTTP:-80}:80"|' "$COMPOSE_FILE"
sed -i 's|"8192:8192"|"${PORT_TRAEFIK_API:-8192}:8192"|' "$COMPOSE_FILE"
sed -i 's|"8080:8080"|"${PORT_TRAEFIK_DASHBOARD:-8080}:8080"|' "$COMPOSE_FILE"

# phpMyAdmin
sed -i 's|"0.0.0.0:8086:80"|"0.0.0.0:${PORT_PHPMYADMIN:-8086}:80"|' "$COMPOSE_FILE"

# Mailpit
sed -i 's|"0.0.0.0:8025:8025"|"0.0.0.0:${PORT_MAILPIT_WEB:-8025}:8025"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:1025:1025"|"0.0.0.0:${PORT_MAILPIT_SMTP:-1025}:1025"|' "$COMPOSE_FILE"

# SpamAssassin
sed -i 's|783:783|${PORT_SPAMASSASSIN:-783}:783|' "$COMPOSE_FILE"

# rspamd
sed -i 's|"11334:11334"|"${PORT_RSPAMD:-11334}:11334"|' "$COMPOSE_FILE"

# tusd
sed -i 's|"1080:8080"|"${PORT_TUSD:-1080}:8080"|' "$COMPOSE_FILE"

# Status page
sed -i 's|"8081:3000"|"${PORT_STATUS:-8081}:3000"|' "$COMPOSE_FILE"

# AI support helper
sed -i 's|"8083:3000"|"${PORT_AI_SUPPORT:-8083}:3000"|' "$COMPOSE_FILE"

# API v1
sed -i 's|"1023:22"|"${PORT_APIV1_SSH:-1023}:22"|' "$COMPOSE_FILE"
sed -i 's|"83:80"|"${PORT_APIV1_HTTP:-83}:80"|' "$COMPOSE_FILE"
sed -i 's|"8181:80"|"${PORT_APIV1_HTTP2:-8181}:80"|' "$COMPOSE_FILE"

# API v2 and v2-live
sed -i 's|"8193:8192"|"${PORT_APIV2:-8193}:8192"|' "$COMPOSE_FILE"
sed -i 's|"8194:8192"|"${PORT_APIV2_LIVE:-8194}:8192"|' "$COMPOSE_FILE"

# Frontend dev/prod containers
sed -i 's|"0.0.0.0:3002:3002"|"0.0.0.0:${PORT_FREEGLE_DEV_LOCAL:-3002}:3002"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:3005:3002"|"0.0.0.0:${PORT_FREEGLE_DEV_LIVE:-3005}:3002"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:3012:3003"|"0.0.0.0:${PORT_FREEGLE_PROD_LOCAL:-3012}:3003"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:3003:3000"|"0.0.0.0:${PORT_MODTOOLS_DEV_LOCAL:-3003}:3000"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:3006:3000"|"0.0.0.0:${PORT_MODTOOLS_DEV_LIVE:-3006}:3000"|' "$COMPOSE_FILE"
sed -i 's|"0.0.0.0:3013:3001"|"0.0.0.0:${PORT_MODTOOLS_PROD_LOCAL:-3013}:3001"|' "$COMPOSE_FILE"

# Loki
sed -i 's|"3100:3100"|"${PORT_LOKI:-3100}:3100"|' "$COMPOSE_FILE"

# Postfix
sed -i 's|"25:25"|"${PORT_POSTFIX_SMTP:-25}:25"|' "$COMPOSE_FILE"

# MCP sanitizer
sed -i 's|"8084:8080"|"${PORT_MCP_SANITIZER:-8084}:8080"|' "$COMPOSE_FILE"

echo "docker-compose.yml patched. Original saved as docker-compose.yml.original"

# Also generate .env entries
generate_env
echo ""
echo "Add the above lines to your .env file, or run:"
echo "  ./parameterize-ports.sh $OFFSET --env-only >> .env"
